version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # GENERIC_TIMEZONE と TZ を設定することでタイムゾーンを指定できます
      # - GENERIC_TIMEZONE=Asia/Tokyo
      # - TZ=Asia/Tokyo
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows  # ワークフローファイル用のマウントポイント
      - ./credentials:/home/node/credentials # 認証情報ファイル用のマウントポイント
    user: "node" # パーミッションの問題を避けるために node ユーザーで実行
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/sql:/data/sql
    restart: unless-stopped

volumes:
  n8n_data: 
